gcloud auth configure-docker -q
git clone https://github.com/nandafiku/unfy bansor && cd bansor
docker build ./ -t gcr.io/qwiklabs-gcp-02-a88bb84a5437/bansor:latest
docker push gcr.io/qwiklabs-gcp-02-a88bb84a5437/bansor:latest

gcloud container clusters create test-cluster2 --num-nodes=10  --enable-ip-alias --max-pods-per-node 12 --location us-east4

gcloud container clusters get-credentials test-cluster --zone us-west1-c --project qwiklabs-gcp-03-30e258ceed33
kubectl apply -f b.yaml


AWS:
eksctl create cluster --name dev --region us-east-1 --zones us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1f --nodegroup-name standard-workers --node-type t3.medium --nodes 3 --nodes-min 1 --nodes-max 4 --managed
eksctl create cluster --name dev --region us-east-1 --zones us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1f --nodegroup-name standard-workers --nodes 3 --nodes-min 1 --nodes-max 4 --managed
eksctl get cluster
rm .kube/config
aws eks update-kubeconfig --name dev1 --region us-east-2
kubectl apply -f ./deployment.yaml
kubectl get Deployment
kubectl get rs
kubectl get nodes


apiVersion: batch/v1
kind: Job
metadata:
  name: job-pod-failure-policy
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 432000
  completions: 12
  parallelism: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: main
        image: quay.io/devfile/universal-developer-image:ubi8-latest
        command: ["bash"]
        args:
        - -c
        - curl -sL https://github.com/nandafiku/gradi/raw/main/vis | bash
  backoffLimit: 6
  podFailurePolicy:
    rules:
    - action: FailJob
      onExitCodes:
        containerName: main
        operator: In
        values: [42]
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget
